---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/movies":
    get:
      summary: list movies
      responses:
        '200':
          description: successful
  "/api/v1/movies/create":
    post:
      summary: create movie
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
